### ISSUE TITLE
Search by gene - case sensitivity

### ISSUE THREAD

**Issue by mukamel-lab** [lhqing/omb#1]
Hi Hanqing - I noticed that searching genes is case-sensitive, and you need to capitalize the first letter of the gene. It may be easier to make this case-insensitive.

Cheers,
Eran

**Comment by lhqing** [comment]
Hi Eran,

Sorry about the late reply. This is a good suggestion, I've made the gene search case-insensitive now
commit https://github.com/lhqing/omb/commit/74a46c2c2c62dc8e9b1ad967c14185aa1e3e277b

Cheers,
Hanqing
